# Generated by Django 2.1.2 on 2018-10-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('impact', models.IntegerField()),
                ('range', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('magazine', models.IntegerField()),
                ('reload_speed', models.IntegerField()),
                ('handling', models.IntegerField()),
                ('zoom', models.IntegerField()),
                ('inventory_size', models.IntegerField()),
                ('aim_assistance', models.IntegerField()),
                ('recoil_direction', models.IntegerField()),
            ],
        ),
    ]
