# Generated by Django 2.1.2 on 2018-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='aim_assistance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='handling',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='impact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='inventory_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magazine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='recoil_direction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reload_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='stability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='zoom',
            field=models.IntegerField(null=True),
        ),
    ]
